version: "3.9"

services:
  postgres-auth:
    image: postgres:16
    container_name: hplussport-postgres
    environment:
      POSTGRES_DB: hplussport-db
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports: 
      - "5432:5432"
    volumes: 
      - auth-pg-data:/var/lib/postgresql/data

volumes:
  auth-pg-data: